name: Deploy script to DigitalOcean
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: make test

  deploy:
    name: Deploy script to DigitalOcean
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/discord-bot-exchange-rate
            kill -9 $(cat ./pid)
            rm ./out
            rm ./pid
            git fetch --all
            git reset --hard origin/main
            source ./bin/activate
            pip install -r ./requirements.txt
            nohup python3 main.py > ./out 2>&1 </dev/null & echo $! > pid
